name: Kustomize Patch
description: Add Kustomize patches to kustomize.yaml
inputs:
  patches: # id of input
    description: Kustomize patches
    required: true

runs:
  using: composite
  steps:
    - name: Edit kustomization.yaml
      shell: bash
      run: |
        cd ./.github/kustomize
        kustomize edit add patch --kind containerapp --patch '${{ inputs.patches }}'

    - name: Cache kustomization.yaml
      uses: actions/cache/save@v3
      id: cache
      with:
        path: ./.github/kustomize/kustomization.yaml
        key: cache-${{ github.run_id }}
