metadata:
  name: ca-demo

kind: containerapp
name: ca-demo
resourceGroup: rg-platform
type: Microsoft.App/containerApps
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? /subscriptions/2da318e2-604b-4f60-8984-b801b824a602/resourcegroups/rg-platform/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-platform
    : {}
properties:
  managedEnvironmentId: /subscriptions/2da318e2-604b-4f60-8984-b801b824a602/resourceGroups/rg-platform/providers/Microsoft.App/managedEnvironments/cae-platform
  configuration:
    activeRevisionsMode: Single
    secrets:
      - name: authority-secret
        value: AUTHORITY_SECRET
      # - name: registry-secret
      #   value: ACR_PASSWORD
    ingress:
      targetPort: 8080
      external: true
      transport: Auto
    registries:
      - server: acrendochecker.azurecr.io
        identity: /subscriptions/2da318e2-604b-4f60-8984-b801b824a602/resourceGroups/rg-platform/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-platform
        # username: acrendochecker
        # passwordSecretRef: registry-secret
    dapr:
      enabled: true
      appId: auth
      appPort: 8080
      appProtocol: http
  template:
    revisionSuffix: REVISION_SUFFIX
    containers:
      - image: CONTAINER_IMAGE
        name: auth
        env:
          - name: AUTH0_API_IDENTIFIER
            secretRef: auth0-api-identitfier
          - name: AUTH0_DOMAIN
            secretRef: auth0-domain
          - name: AUTH_CLIENT_ID
            secretRef: auth-client-id
          - name: AUTH_CLIENT_SECRET
            secretRef: auth-client-secret
          - name: AUTH_AUDIENCE
            secretRef: audience
        resources:
          cpu: 0.5
          memory: 1Gi
          ephemeralStorage: 1Gi
    scale:
      minReplicas: 1
      maxReplicas: 1
