# Builds and publishes a container image to the Azure container registry,
# then deploys it as a Container App revision.

# Skip this (any) workflow:
#  [skip ci | ci skip | no ci | skip actions | actions skip]
# See https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs

name: Deploy AUTH

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    uses: endo-checker/build/.github/workflows/go-validate.yaml@main
    secrets: inherit
  # HACK: Add patches with secrets to kustomization.yaml and cache 
  # for use by the 'deploy' job.
  patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Edit kustomization.yaml
        run: |
          cd ./.github/kustomize
          kustomize edit add patch --kind containerapp --patch '[
            {"op": "add", "path": "/properties/configuration/secrets/-", "value": {"name": "auth0-api-identitfier", "value": "${{ secrets.AUTH0_API_IDENTIFIER }}"}},
            {"op": "add", "path": "/properties/configuration/secrets/-", "value": {"name": "auth0-domain", "value": "${{ secrets.AUTH0_DOMAIN }}"}}, 
            {"op": "add", "path": "/properties/configuration/secrets/-", "value": {"name": "auth-client-id", "value": "${{ secrets.AUTH_CLIENT_ID }}"}},
            {"op": "add", "path": "/properties/configuration/secrets/-", "value": {"name": "auth-client-secret", "value": "${{ secrets.AUTH_CLIENT_SECRET }}"}},
            {"op": "add", "path": "/properties/configuration/secrets/-", "value": {"name": "audience", "value": "${{ secrets.AUTH_AUDIENCE }}"}}
          ]'

      - name: Cache kustomization.yaml
        uses: actions/cache/save@v3
        id: cache
        with:
          path: ./.github/kustomize/kustomization.yaml
          key: cache-${{ github.run_id }}

  deploy:
    needs: 
      - validate
      - patch 
    uses: credibil/build/.github/workflows/container-app-deploy.yaml@main
    secrets: inherit
    with:
      resourceGroup: rg-platform
      acrName: acrendochecker
      cacheKey: cache-${{ github.run_id }}
      customTemplate: true

  route:
    needs: deploy
    uses: credibil/build/.github/workflows/container-app-route.yaml@main
    secrets: inherit
    with:
      resourceGroup: rg-platform
      trafficMode: latest
